-- users table data
INSERT INTO users (first_name, last_name, user_password, username, profession, profile_pic) VALUES ('Harshith', 'Cariappa', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'HarshithCariappa', 'Senior Software Engineer II', '/images/harshith.jpg');
INSERT INTO users (first_name, last_name, user_password, username, profession, profile_pic) VALUES ('Vivek', 'Texeira', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'VivekTexeira', 'Technical Lead', '/images/vivek.jpg');
INSERT INTO users (first_name, last_name, user_password, username, profession, profile_pic) VALUES ('Amitha', 'Moily', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'AmithaMoily', 'Team Manager', '/images/amitha.jpg');
INSERT INTO users (first_name, last_name, user_password, username, profession, profile_pic) VALUES ('Rameez', 'Raza', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', 'RameezRaza', 'Senior Software Engineer II', '/images/rameez.jpg');

-- blogs table data
INSERT INTO blogs (blog_title, blog_content, created_by, modified_on, image_path) VALUES ('Workshop 1 at SDIT', 'This blog is about the first workshop conducted in SDIT. Topics covered : Docker, docker compose and linux commands. Github url : https://github.com/Unicourt/Website-Workshop1 All the details of the workshop are in this repository', 2, NOW(), '/images/workshop1.jpg');
INSERT INTO blogs (blog_title, blog_content, created_by, modified_on, image_path) VALUES ('Workshop 2 at SDIT','This blog is about the second workshop conducted in SDIT. Topics covered : HTML and CSS  Github url : https://github.com/Unicourt/Website-Workshop2 All the details of the workshop are in this repository', 4, NOW(), '/images/workshop2.jpg');
INSERT INTO blogs (blog_title, blog_content, created_by, modified_on, image_path) VALUES ('Workshop 3 at SDIT','This blog is about the third workshop conducted in SDIT. Topics covered : PHP and Postgres  Github url : https://github.com/Unicourt/Website-Workshop3 All the details of the workshop are in this repository', 1, NOW(), '/images/workshop3.jpg');
INSERT INTO blogs (blog_title, blog_content, created_by, modified_on, image_path) VALUES ('Feedback from team Manager', 'Imaging something good here. With great power comes great responsibility. Darr ke aage jeet hain. Kabhi kushi Kabhi gum, WAKANDA FOREVER. #RCB #ESALACUPNAMDE ', 3, NOW(), '/images/manager.jpg');
INSERT INTO blogs (blog_title, blog_content, created_by, modified_on, image_path) VALUES ('Things learnt in Mangalore', ' Dada ya, Dala ijji, Vanas aanda, Barpe, StateBank is a bus stop name, Ammer is not mom ??? and Appe is not Dad?? WHYYYYYY????  . Bangude , Buthai are types of fish. You go to beach in one color and come out as if someone changed your contrast.', 1, NOW(), '/images/mangalore.jpg');